project_id = "clgdigtnhoqwnmjwyiwh"

[functions.preview-transactional-email]
verify_jwt = false

[functions.mcp]
verify_jwt = false

[functions.send-report-calcolatore]
verify_jwt = false

[functions.send-lead-landing4]
verify_jwt = false
