// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-pricing.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var PLANS = [
  {
    id: "base",
    name: "Base",
    price_eur_per_month: 14.9,
    description: "Ticketing guasti su WhatsApp, dashboard immobili, tecnici verificati Hommi.",
    best_for: "Piccoli portfolio (1-14 alloggi) che vogliono iniziare."
  },
  {
    id: "premium",
    name: "Premium",
    price_eur_per_month: 29.9,
    description: "Tutto di Base + tecnico dedicato, gestione end-to-end degli interventi, sopralluogo incluso.",
    best_for: "Property manager e agenzie con 15-50 alloggi."
  },
  {
    id: "plus",
    name: "Plus",
    price_eur_per_month: 39.9,
    description: "Tutto di Premium + account manager dedicato, report per proprietario, SLA garantiti.",
    best_for: "Portfolio grandi (50+ alloggi) e operazioni multi-cliente."
  }
];
var get_pricing_default = defineTool({
  name: "get_pricing",
  title: "Get Hommi pricing plans",
  description: "Restituisce i piani di abbonamento Hommi (Base, Premium, Plus) con prezzo mensile in euro per immobile, descrizione e profilo target.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(PLANS, null, 2) }],
    structuredContent: { plans: PLANS, currency: "EUR", billing: "monthly_per_property" }
  })
});

// src/lib/mcp/tools/get-service-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var INFO = {
  company: "Hommi (S9 s.r.l. SB)",
  tagline: "Piattaforma di gestione manutenzione per immobili in affitto: ticketing su WhatsApp, tecnici verificati, costi trasparenti.",
  target_audience: [
    "Property manager",
    "Agenzie immobiliari",
    "Host Airbnb e case vacanza professionali"
  ],
  services: [
    "Ticketing guasti (apertura via WhatsApp o piattaforma)",
    "Rete di tecnici e manutentori verificati",
    "Coordinamento interventi end-to-end",
    "Dashboard multi-portfolio",
    "Report costi per proprietario"
  ],
  geographic_scope: {
    cities: ["Milano", "Monza", "Como", "Torino", "Lecco"],
    note: "Il servizio operativo Hommi \xE8 disponibile solo in queste 5 citt\xE0. Non sono coperte altre zone d'Italia."
  },
  operations_channels: ["WhatsApp", "Piattaforma web Hommi"],
  website: "https://hommi.it"
};
var get_service_info_default = defineTool2({
  name: "get_service_info",
  title: "Get Hommi service info",
  description: "Restituisce informazioni generali sul servizio Hommi: descrizione, target, servizi offerti, citt\xE0 coperte (Milano, Monza, Como, Torino, Lecco) e canali operativi.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(INFO, null, 2) }],
    structuredContent: INFO
  })
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var CONTACTS = {
  website: "https://hommi.it",
  calcolatore_costi: "https://hommi.it/calcolatore",
  prenota_call: "https://prenota.hommi.it/richiedi-accesso",
  candidature_manutentori: "https://hommi.it/per-manutentori-domanda",
  ticket_supporto: "https://hommi.it/ticket",
  company: "S9 s.r.l. SB"
};
var get_contact_info_default = defineTool3({
  name: "get_contact_info",
  title: "Get Hommi contact links",
  description: "Restituisce i principali link di contatto Hommi: sito, calcolatore costi, prenotazione call demo, form candidatura manutentori, apertura ticket.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(CONTACTS, null, 2) }],
    structuredContent: CONTACTS
  })
});

// src/lib/mcp/tools/stima-costo-manutenzione.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var stima_costo_manutenzione_default = defineTool4({
  name: "stima_costo_manutenzione",
  title: "Stima costo manutenzione annuo",
  description: "Fornisce una stima indicativa del costo annuo di manutenzione di un portfolio immobiliare, in base al numero di immobili e al tipo di locazione (breve termine o medio-lungo termine). I risultati sono approssimativi e riflettono medie di mercato Hommi.",
  inputSchema: {
    numero_immobili: z.number().int().min(1).max(500).describe("Numero di immobili gestiti"),
    tipo_locazione: z.enum(["breve_termine", "medio_lungo_termine"]).describe("Tipo di locazione: breve termine (Airbnb) o medio-lungo termine")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ numero_immobili, tipo_locazione }) => {
    const costoMedioIntervento = 180;
    const interventiPerImmobile = tipo_locazione === "breve_termine" ? 4 : 2;
    const totaleInterventi = numero_immobili * interventiPerImmobile;
    const costoTotaleAnnuo = totaleInterventi * costoMedioIntervento;
    const result = {
      input: { numero_immobili, tipo_locazione },
      stima: {
        interventi_annui_stimati: totaleInterventi,
        costo_medio_intervento_eur: costoMedioIntervento,
        costo_totale_annuo_eur: costoTotaleAnnuo,
        costo_medio_per_immobile_eur: Math.round(costoTotaleAnnuo / numero_immobili)
      },
      note: "Stima indicativa basata su medie di mercato. Per una stima personalizzata usare https://hommi.it/calcolatore"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-faq.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var FAQ = [
  {
    q: "In quali citt\xE0 opera Hommi?",
    a: "Hommi opera esclusivamente a Milano, Monza, Como, Torino e Lecco. Non copriamo altre citt\xE0 italiane."
  },
  {
    q: "Come si apre un ticket di manutenzione?",
    a: "I ticket si aprono direttamente via WhatsApp o dalla piattaforma web Hommi. Non c'\xE8 un'app dedicata."
  },
  {
    q: "Quanto costa Hommi?",
    a: "Tre piani per immobile/mese: Base \u20AC14.90, Premium \u20AC29.90, Plus \u20AC39.90. Nessun vincolo annuale."
  },
  {
    q: "Come vengono selezionati i tecnici?",
    a: "I manutentori Hommi passano un processo di selezione (verifica documenti, referenze, prove pratiche). Vengono valutati continuamente in base a puntualit\xE0, qualit\xE0 del lavoro e feedback dei clienti."
  },
  {
    q: "Cosa succede se un intervento non \xE8 risolutivo?",
    a: "Hommi garantisce il ripristino: se un intervento non risolve il problema, viene rifatto senza costi aggiuntivi entro i termini di garanzia previsti."
  },
  {
    q: "Posso vedere i costi in anticipo?",
    a: "S\xEC. Hommi lavora con costi trasparenti: preventivo prima dell'intervento e rendicontazione dettagliata per ogni ticket."
  }
];
var list_faq_default = defineTool5({
  name: "list_faq",
  title: "List Hommi FAQ",
  description: "Restituisce le domande frequenti pubbliche su Hommi: citt\xE0 coperte, ticketing, prezzi, selezione tecnici, garanzie, trasparenza costi.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(FAQ, null, 2) }],
    structuredContent: { faq: FAQ }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "hommi-mcp",
  title: "Hommi MCP",
  version: "0.1.0",
  instructions: "Tool pubblici per informarsi su Hommi, piattaforma italiana di gestione manutenzione immobili (Milano, Monza, Como, Torino, Lecco). Usa get_service_info per una panoramica, get_pricing per i piani, stima_costo_manutenzione per una stima costi annuale, list_faq per le domande frequenti, get_contact_info per i link utili (sito, calcolatore, prenotazione call).",
  tools: [get_service_info_default, get_pricing_default, stima_costo_manutenzione_default, list_faq_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
